# Generated by Django 4.1.11 on 2023-10-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="link",
            new_name="ProductLink",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="ProductName",
        ),
        migrations.AddField(
            model_name="product",
            name="ProductBrand",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="ProductImageUrl",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="ProductPrice",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="ProductRating",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="ProductReviews",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="Store",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
